# Generated by Django 4.0.3 on 2022-04-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_order_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
    ]
