# Generated by Django 4.0.3 on 2022-04-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_order_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock',
        ),
    ]
