# Generated by Django 4.0.3 on 2022-04-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_quantity_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='threshold_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
